using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

namespace GAF.Gen;

/// <summary>
/// Incremental Source Generator that automatically generates Float32 versions of all Float64 code.
/// Processes .cs files containing "Float64" in their path and applies Float32SyntaxRewriter transformations.
/// </summary>
[Generator]
public class F32Gen : IIncrementalGenerator
{
    private const string GeneratorName = "Float32Generator";
    private const string GeneratorVersion = "1.0.0";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register post-initialization output (optional: add marker attributes)
        context.RegisterPostInitializationOutput(ctx =>
        {
            // Add a marker attribute so consumer code can detect generated files
            var markerAttribute = @"// <auto-generated />
// Generated by Float32SourceGenerator v" + GeneratorVersion + @"
namespace GeometricAlgebraFulcrumLib.Generated
{
    [System.AttributeUsage(System.AttributeTargets.All)]
    internal class GeneratedFloat32Attribute : System.Attribute
    {
        public string OriginalFile { get; }
        public GeneratedFloat32Attribute(string originalFile) => OriginalFile = originalFile;
    }
}
";
            ctx.AddSource("Float32GeneratorMarker.g.cs", SourceText.From(markerAttribute, Encoding.UTF8));

            // Generate Float32 Extension Methods for LinBasisVector
            var linBasisVectorExtensions = GenerateLinBasisVectorExtensions();
            ctx.AddSource("LinBasisVectorFloat32Extensions.g.cs", SourceText.From(linBasisVectorExtensions, Encoding.UTF8));

            // Generate Float32 Extension Methods for ILinFloat32Vector interfaces (3 separate files)
            var linVectorInterfaceExtensions2D = GenerateLinVectorInterfaceExtensions2D();
            ctx.AddSource("LinVectorInterfaceFloat32Extensions2D.g.cs", SourceText.From(linVectorInterfaceExtensions2D, Encoding.UTF8));

            var linVectorInterfaceExtensions3D = GenerateLinVectorInterfaceExtensions3D();
            ctx.AddSource("LinVectorInterfaceFloat32Extensions3D.g.cs", SourceText.From(linVectorInterfaceExtensions3D, Encoding.UTF8));

            var linVectorInterfaceExtensions4D = GenerateLinVectorInterfaceExtensions4D();
            ctx.AddSource("LinVectorInterfaceFloat32Extensions4D.g.cs", SourceText.From(linVectorInterfaceExtensions4D, Encoding.UTF8));

            // Generate Float32 Extension Methods for IPair/ITriplet with Float32Scalar
            var tupleExtensions = GenerateTupleExtensions();
            ctx.AddSource("TupleFloat32Extensions.g.cs", SourceText.From(tupleExtensions, Encoding.UTF8));

            // Generate Float32 Extension Methods for MathNet.Numerics types
            var mathNetExtensions = GenerateMathNetExtensions();
            ctx.AddSource("MathNetFloat32Extensions.g.cs", SourceText.From(mathNetExtensions, Encoding.UTF8));

            // Generate Float32 Extension Methods for XGa validation methods
            var xgaExtensions = GenerateXGaExtensions();
            ctx.AddSource("XGaFloat32Extensions.g.cs", SourceText.From(xgaExtensions, Encoding.UTF8));

            // Generate Float32 Extension Methods for XGa Vector/Multivector conversions
            var xgaVectorExtensions = GenerateXGaVectorExtensions();
            ctx.AddSource("XGaVectorFloat32Extensions.g.cs", SourceText.From(xgaVectorExtensions, Encoding.UTF8));

            // Generate Float32 Extension Methods for LinBasisVectorPair3D (Quaternion conversions)
            var linBasisVectorPair3DExtensions = GenerateLinBasisVectorPair3DExtensions();
            ctx.AddSource("LinBasisVectorPair3DFloat32Extensions.g.cs", SourceText.From(linBasisVectorPair3DExtensions, Encoding.UTF8));

            // Generate Float32 Extension Methods for Random utilities
            var randomExtensions = GenerateRandomExtensions();
            ctx.AddSource("RandomFloat32Extensions.g.cs", SourceText.From(randomExtensions, Encoding.UTF8));

            // Generate Float32 Extension Methods for MathNet.Numerics interop (double/Vector<double> types)
            var mathNetInteropExtensions = GenerateMathNetInteropExtensions();
            ctx.AddSource("MathNetInteropFloat32Extensions.g.cs", SourceText.From(mathNetInteropExtensions, Encoding.UTF8));
        });

        // Create incremental pipeline for Float64 files
        // IMPORTANT: Only process files that:
        // 1. Have "Float64" in their path (actual Float64 code)
        // 2. Do NOT have "Float32" in their path (skip manually created Float32 code)
        // 3. Are .cs files
        // 4. Not in obj/bin directories
        var float64Files = context.AdditionalTextsProvider
            .Where(file =>
            {
                var path = file.Path;
                return path.IndexOf("Float64", StringComparison.OrdinalIgnoreCase) >= 0 &&
                       path.IndexOf("Float32", StringComparison.OrdinalIgnoreCase) < 0 &&  // NEW: Skip existing Float32 files
                       path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase) &&
                       path.IndexOf("\\obj\\", StringComparison.OrdinalIgnoreCase) < 0 &&
                       path.IndexOf("\\bin\\", StringComparison.OrdinalIgnoreCase) < 0;
            })
            .Select((file, ct) => file);

        // Register source output for each Float64 file
        context.RegisterSourceOutput(float64Files, (ctx, file) =>
        {
            GenerateFloat32Source(ctx, file);
        });
    }

    private static void GenerateFloat32Source(
        SourceProductionContext context,
        AdditionalText float64File)
    {
        try
        {
            // Read source text
            var sourceText = float64File.GetText(context.CancellationToken);
            if (sourceText == null || sourceText.Length == 0)
                return;

            // Parse to syntax tree
            var syntaxTree = CSharpSyntaxTree.ParseText(
                sourceText,
                options: CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest),
                cancellationToken: context.CancellationToken
            );

            // Check for parse errors
            var diagnostics = syntaxTree.GetDiagnostics(context.CancellationToken);
            if (diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error))
            {
                // Report diagnostic but don't fail
                var descriptor = new DiagnosticDescriptor(
                    id: "FLOAT32GEN002",
                    title: "Float32 Source Parse Error",
                    messageFormat: "Could not parse Float64 source file {0}: {1}",
                    category: GeneratorName,
                    DiagnosticSeverity.Warning,
                    isEnabledByDefault: true
                );

                var firstError = diagnostics.First(d => d.Severity == DiagnosticSeverity.Error);
                context.ReportDiagnostic(Diagnostic.Create(
                    descriptor,
                    Location.None,
                    float64File.Path,
                    firstError.GetMessage()
                ));
                return;
            }

            // Apply rewriter
            var rewriter = new Float32SyntaxRewriter();
            var root = syntaxTree.GetRoot(context.CancellationToken);
            var newRoot = rewriter.Visit(root);

            if (newRoot == null)
                return;

            // Generate output
            var float32Code = newRoot.ToFullString();
            if (string.IsNullOrEmpty(float32Code))
                return;

            // Add header comment with generation info
            var header = $@"// <auto-generated />
// Generated by {GeneratorName} v{GeneratorVersion}
// Source: {Path.GetFileName(float64File.Path)}
// DO NOT EDIT - Changes will be overwritten

";
            float32Code = header + float32Code;

            // Generate short, structured hint name to avoid path length issues
            var hintName = GenerateShortHintName(float64File.Path);

            // Add source to compilation
            context.AddSource(
                hintName,
                SourceText.From(float32Code, Encoding.UTF8)
            );
        }
        catch (Exception ex)
        {
            // Report diagnostic for any exceptions
            var descriptor = new DiagnosticDescriptor(
                id: "FLOAT32GEN001",
                title: "Float32 Generation Error",
                messageFormat: "Error generating Float32 from {0}: {1}",
                category: GeneratorName,
                DiagnosticSeverity.Error,
                isEnabledByDefault: true
            );

            context.ReportDiagnostic(Diagnostic.Create(
                descriptor,
                Location.None,
                float64File.Path,
                ex.Message
            ));
        }
    }

    /// <summary>
    /// Generates a hint name that preserves the folder structure.
    /// Format: [ModuleName]/Float32/[SubPath]/[ClassName].g.cs
    /// Example: LinearAlgebra/Float32/Vectors/Space3D/LinFloat32Vector3D.g.cs
    /// </summary>
    private static string GenerateShortHintName(string float64Path)
    {
        try
        {
            // Normalize path separators
            var normalizedPath = float64Path.Replace('\\', '/');

            // Extract filename
            var fileName = Path.GetFileNameWithoutExtension(normalizedPath);
            var float32FileName = fileName.Replace("Float64", "Float32");

            // Detect module from path and extract relative path after it
            string moduleName = null;
            string relativePath = null;

            if (normalizedPath.IndexOf("/Scalars/Float64", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                moduleName = "Scalars";
                var idx = normalizedPath.IndexOf("/Scalars/Float64", StringComparison.OrdinalIgnoreCase);
                relativePath = normalizedPath.Substring(idx + "/Scalars/Float64".Length);
            }
            else if (normalizedPath.IndexOf("/LinearAlgebra/Float64", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                moduleName = "LinearAlgebra";
                var idx = normalizedPath.IndexOf("/LinearAlgebra/Float64", StringComparison.OrdinalIgnoreCase);
                relativePath = normalizedPath.Substring(idx + "/LinearAlgebra/Float64".Length);
            }
            else if (normalizedPath.IndexOf("/GeometricAlgebra/Float64", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                moduleName = "GeometricAlgebra";
                var idx = normalizedPath.IndexOf("/GeometricAlgebra/Float64", StringComparison.OrdinalIgnoreCase);
                relativePath = normalizedPath.Substring(idx + "/GeometricAlgebra/Float64".Length);
            }
            else if (normalizedPath.IndexOf("/Polynomials/Float64", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                moduleName = "Polynomials";
                var idx = normalizedPath.IndexOf("/Polynomials/Float64", StringComparison.OrdinalIgnoreCase);
                relativePath = normalizedPath.Substring(idx + "/Polynomials/Float64".Length);
            }
            else if (normalizedPath.IndexOf("/CGa/Float64", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                moduleName = "CGa";
                var idx = normalizedPath.IndexOf("/CGa/Float64", StringComparison.OrdinalIgnoreCase);
                relativePath = normalizedPath.Substring(idx + "/CGa/Float64".Length);
            }
            else if (normalizedPath.IndexOf("/PGa/Float64", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                moduleName = "PGa";
                var idx = normalizedPath.IndexOf("/PGa/Float64", StringComparison.OrdinalIgnoreCase);
                relativePath = normalizedPath.Substring(idx + "/PGa/Float64".Length);
            }
            else if (normalizedPath.IndexOf("/VGa/Float64", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                moduleName = "VGa";
                var idx = normalizedPath.IndexOf("/VGa/Float64", StringComparison.OrdinalIgnoreCase);
                relativePath = normalizedPath.Substring(idx + "/VGa/Float64".Length);
            }
            else
            {
                // Fallback: use just the filename
                return $"{float32FileName}.g.cs";
            }

            // Clean up relative path: remove leading slash and filename
            if (!string.IsNullOrEmpty(relativePath))
            {
                relativePath = relativePath.TrimStart('/');
                var lastSlash = relativePath.LastIndexOf('/');
                if (lastSlash >= 0)
                {
                    relativePath = relativePath.Substring(0, lastSlash);
                }
                else
                {
                    relativePath = "";
                }
            }

            // Build hint name with folder structure: [ModuleName]/Float32/[SubPath]/[FileName].g.cs
            string hintName;
            if (!string.IsNullOrEmpty(relativePath))
            {
                hintName = $"{moduleName}/Float32/{relativePath}/{float32FileName}.g.cs";
            }
            else
            {
                hintName = $"{moduleName}/Float32/{float32FileName}.g.cs";
            }

            // Sanitize hint name (remove any invalid characters)
            hintName = hintName.Replace("<", "").Replace(">", "").Replace(":", "");

            return hintName;
        }
        catch
        {
            // Fallback: use just the filename
            var fileName = Path.GetFileNameWithoutExtension(float64Path);
            return $"{fileName.Replace("Float64", "Float32")}.g.cs";
        }
    }

    private static string GenerateLinBasisVectorExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for LinBasisVector to support Float32 conversions
// DO NOT EDIT - Changes will be overwritten

using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Basis;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space2D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space3D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space4D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.SpaceND;

namespace GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Basis;

public static class LinBasisVectorFloat32Extensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector2D ToLinFloat32Vector2D(this LinBasisVector basisVector)
    {
        if (basisVector.IsPositive)
            return basisVector.Index switch
            {
                0 => LinFloat32Vector2D.E1,
                1 => LinFloat32Vector2D.E2,
                _ => throw new System.InvalidOperationException()
            };

        return basisVector.Index switch
        {
            0 => LinFloat32Vector2D.NegativeE1,
            1 => LinFloat32Vector2D.NegativeE2,
            _ => throw new System.InvalidOperationException()
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector2D ToLinFloat32Vector2D(this LinBasisVector basisVector, float scalingFactor)
    {
        if (basisVector.IsPositive)
            return basisVector.Index switch
            {
                0 => LinFloat32Vector2D.Create(scalingFactor, 0),
                1 => LinFloat32Vector2D.Create(0, scalingFactor),
                _ => throw new System.InvalidOperationException()
            };

        return basisVector.Index switch
        {
            0 => LinFloat32Vector2D.Create(-scalingFactor, 0),
            1 => LinFloat32Vector2D.Create(0, -scalingFactor),
            _ => throw new System.InvalidOperationException()
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this LinBasisVector basisVector)
    {
        if (basisVector.IsPositive)
            return basisVector.Index switch
            {
                0 => LinFloat32Vector3D.E1,
                1 => LinFloat32Vector3D.E2,
                2 => LinFloat32Vector3D.E3,
                _ => throw new System.InvalidOperationException()
            };

        return basisVector.Index switch
        {
            0 => LinFloat32Vector3D.NegativeE1,
            1 => LinFloat32Vector3D.NegativeE2,
            2 => LinFloat32Vector3D.NegativeE3,
            _ => throw new System.InvalidOperationException()
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this LinBasisVector basisVector, float scalingFactor)
    {
        if (basisVector.IsPositive)
            return basisVector.Index switch
            {
                0 => LinFloat32Vector3D.Create(scalingFactor, 0, 0),
                1 => LinFloat32Vector3D.Create(0, scalingFactor, 0),
                2 => LinFloat32Vector3D.Create(0, 0, scalingFactor),
                _ => throw new System.InvalidOperationException()
            };

        return basisVector.Index switch
        {
            0 => LinFloat32Vector3D.Create(-scalingFactor, 0, 0),
            1 => LinFloat32Vector3D.Create(0, -scalingFactor, 0),
            2 => LinFloat32Vector3D.Create(0, 0, -scalingFactor),
            _ => throw new System.InvalidOperationException()
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this LinBasisVector basisVector)
    {
        if (basisVector.IsPositive)
            return basisVector.Index switch
            {
                0 => LinFloat32Vector4D.E1,
                1 => LinFloat32Vector4D.E2,
                2 => LinFloat32Vector4D.E3,
                3 => LinFloat32Vector4D.E4,
                _ => throw new System.InvalidOperationException()
            };

        return basisVector.Index switch
        {
            0 => LinFloat32Vector4D.NegativeE1,
            1 => LinFloat32Vector4D.NegativeE2,
            2 => LinFloat32Vector4D.NegativeE3,
            3 => LinFloat32Vector4D.NegativeE4,
            _ => throw new System.InvalidOperationException()
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this LinBasisVector basisVector, float scalingFactor)
    {
        if (basisVector.IsPositive)
            return basisVector.Index switch
            {
                0 => LinFloat32Vector4D.Create(scalingFactor, 0, 0, 0),
                1 => LinFloat32Vector4D.Create(0, scalingFactor, 0, 0),
                2 => LinFloat32Vector4D.Create(0, 0, scalingFactor, 0),
                3 => LinFloat32Vector4D.Create(0, 0, 0, scalingFactor),
                _ => throw new System.InvalidOperationException()
            };

        return basisVector.Index switch
        {
            0 => LinFloat32Vector4D.Create(-scalingFactor, 0, 0, 0),
            1 => LinFloat32Vector4D.Create(0, -scalingFactor, 0, 0),
            2 => LinFloat32Vector4D.Create(0, 0, -scalingFactor, 0),
            3 => LinFloat32Vector4D.Create(0, 0, 0, -scalingFactor),
            _ => throw new System.InvalidOperationException()
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this LinBasisVector basisVector)
    {
        if (basisVector.IsZero)
            return LinFloat32Vector.Zero;

        var basisScalarDictionary =
            new GeometricAlgebraFulcrumLib.Utilities.Structures.Dictionary.SingleItemDictionary<int, float>(
                basisVector.Index,
                basisVector.IsPositive ? 1f : -1f
            );

        return LinFloat32Vector.Create(basisScalarDictionary);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this LinBasisVector basisVector, int dimensions)
    {
        var composer = LinFloat32VectorComposer.Create();

        composer.SetTerm(
            basisVector.Index,
            basisVector.IsPositive ? 1f : -1f
        );

        return composer.GetVector();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this LinBasisVector basisVector, int dimensions, float scalingFactor)
    {
        var composer = LinFloat32VectorComposer.Create();

        composer.SetTerm(
            basisVector.Index,
            basisVector.IsPositive ? scalingFactor : -scalingFactor
        );

        return composer.GetVector();
    }
}
";
    }

    private static string GenerateLinVectorInterfaceExtensions2D()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for ILinFloat32Vector2D
// DO NOT EDIT - Changes will be overwritten

using System.Runtime.CompilerServices;

namespace GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space2D;

public static class LinVectorInterfaceFloat32Extensions2D
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector2D ToLinFloat32Vector2D(this ILinFloat32Vector2D vector)
    {
        return vector is LinFloat32Vector2D v
            ? v
            : LinFloat32Vector2D.Create(vector.X, vector.Y);
    }
}
";
    }

    private static string GenerateLinVectorInterfaceExtensions3D()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for ILinFloat32Vector3D
// DO NOT EDIT - Changes will be overwritten

using System.Runtime.CompilerServices;

namespace GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space3D;

public static class LinVectorInterfaceFloat32Extensions3D
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this ILinFloat32Vector3D vector)
    {
        return vector is LinFloat32Vector3D v
            ? v
            : LinFloat32Vector3D.Create(vector.X, vector.Y, vector.Z);
    }
}
";
    }

    private static string GenerateLinVectorInterfaceExtensions4D()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for ILinFloat32Vector4D
// DO NOT EDIT - Changes will be overwritten

using System.Runtime.CompilerServices;

namespace GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space4D;

public static class LinVectorInterfaceFloat32Extensions4D
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this ILinFloat32Vector4D vector)
    {
        return vector is LinFloat32Vector4D v
            ? v
            : LinFloat32Vector4D.Create(vector.X, vector.Y, vector.Z, vector.W);
    }
}
";
    }

    private static string GenerateTupleExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for IPair/ITriplet/IQuad with Float32Scalar
// DO NOT EDIT - Changes will be overwritten

using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space2D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space3D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space4D;
using GeometricAlgebraFulcrumLib.Algebra.Scalars.Float32;
using GeometricAlgebraFulcrumLib.Utilities.Structures.Tuples;

namespace GeometricAlgebraFulcrumLib.Algebra.Scalars.Float32;

public static class TupleFloat32Extensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector2D ToLinFloat32Vector2D(this IPair<Float32Scalar> tuple)
    {
        return LinFloat32Vector2D.Create(
            tuple.Item1.ScalarValue,
            tuple.Item2.ScalarValue
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this ITriplet<Float32Scalar> tuple)
    {
        return LinFloat32Vector3D.Create(
            tuple.Item1.ScalarValue,
            tuple.Item2.ScalarValue,
            tuple.Item3.ScalarValue
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this IQuad<Float32Scalar> tuple)
    {
        return LinFloat32Vector4D.Create(
            tuple.Item1.ScalarValue,
            tuple.Item2.ScalarValue,
            tuple.Item3.ScalarValue,
            tuple.Item4.ScalarValue
        );
    }
}
";
    }

    private static string GenerateMathNetExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for MathNet.Numerics types
// DO NOT EDIT - Changes will be overwritten

using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space2D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space3D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space4D;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.SpaceND;
using MathNet.Numerics.LinearAlgebra;

namespace GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32;

public static class MathNetFloat32Extensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this Vector<double> vector)
    {
        var count = vector.Count;
        var array = new float[count];
        for (var i = 0; i < count; i++)
            array[i] = (float)vector[i];

        return LinFloat32Vector.Create(array);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this float[] array)
    {
        return LinFloat32Vector.Create(array);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this int vSpaceDimensions)
    {
        return LinFloat32Vector.Create(vSpaceDimensions);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this Vector<double> vector)
    {
        return LinFloat32Vector3D.Create(
            (float)vector[0],
            (float)vector[1],
            (float)vector[2]
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this Vector<float> vector)
    {
        return LinFloat32Vector3D.Create(
            vector[0],
            vector[1],
            vector[2]
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this float[] array)
    {
        return LinFloat32Vector3D.Create(
            array[0],
            array[1],
            array[2]
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this Vector<double> vector)
    {
        return LinFloat32Vector4D.Create(
            (float)vector[0],
            (float)vector[1],
            (float)vector[2],
            (float)vector[3]
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this Vector<float> vector)
    {
        return LinFloat32Vector4D.Create(
            vector[0],
            vector[1],
            vector[2],
            vector[3]
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this float[] array)
    {
        return LinFloat32Vector4D.Create(
            array[0],
            array[1],
            array[2],
            array[3]
        );
    }

    // NOTE: ToComplex() for Matrix<float> is now in MathNetInteropFloat32Extensions
    // It returns Matrix<Complex>, not Matrix<double>

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this float[] itemArray)
    {
        return LinFloat32Vector.Create(itemArray);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this double[] itemArray)
    {
        var count = itemArray.Length;
        var floatArray = new float[count];
        for (var i = 0; i < count; i++)
            floatArray[i] = (float)itemArray[i];

        return LinFloat32Vector.Create(floatArray);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateUnitLinFloat32Vector(this float[] itemArray)
    {
        var vector = LinFloat32Vector.Create(itemArray);
        return vector / vector.ENorm();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateUnitLinFloat32Vector(this double[] itemArray)
    {
        var count = itemArray.Length;
        var floatArray = new float[count];
        for (var i = 0; i < count; i++)
            floatArray[i] = (float)itemArray[i];

        var vector = LinFloat32Vector.Create(floatArray);
        return vector / vector.ENorm();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this Vector<float> vector)
    {
        return LinFloat32Vector.Create(vector);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this IReadOnlyList<float> itemList)
    {
        var count = itemList.Count;
        var array = new float[count];
        for (var i = 0; i < count; i++)
            array[i] = itemList[i];

        return LinFloat32Vector.Create(array);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this IEnumerable<float> items)
    {
        return LinFloat32Vector.Create(items.ToArray());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this IEnumerable<float> items)
    {
        return LinFloat32Vector.Create(items.ToArray());
    }

    /// <summary>
    /// Convert IEnumerable double to Float32Vector - used for MathNet.Numerics interop
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this IEnumerable<double> items)
    {
        return LinFloat32Vector.Create(items.Select(x => (float)x).ToArray());
    }

    /// <summary>
    /// Convert IEnumerable double to Float32Vector - used for MathNet.Numerics interop
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this IEnumerable<double> items)
    {
        return LinFloat32Vector.Create(items.Select(x => (float)x).ToArray());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateUnitLinFloat32Vector(this IReadOnlyList<float> itemList)
    {
        var count = itemList.Count;
        var array = new float[count];
        for (var i = 0; i < count; i++)
            array[i] = itemList[i];

        var vector = LinFloat32Vector.Create(array);
        return vector / vector.ENorm();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateUnitLinFloat32Vector(this IReadOnlyDictionary<int, float> indexScalarDictionary)
    {
        var vector = LinFloat32Vector.Create(indexScalarDictionary);
        return vector / vector.ENorm();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this System.Collections.Generic.Dictionary<int, float> indexScalarDictionary)
    {
        return LinFloat32Vector.Create(indexScalarDictionary);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this Vector<double> vector)
    {
        var count = vector.Count;
        var array = new float[count];
        for (var i = 0; i < count; i++)
            array[i] = (float)vector[i];

        return LinFloat32Vector.Create(array);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector3D ToLinFloat32Vector3D(this IReadOnlyList<float> array)
    {
        return LinFloat32Vector3D.Create(
            array[0],
            array[1],
            array[2]
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector4D ToLinFloat32Vector4D(this IReadOnlyList<float> array)
    {
        return LinFloat32Vector4D.Create(
            array[0],
            array[1],
            array[2],
            array[3]
        );
    }
}
";
    }

    private static string GenerateXGaExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for XGa validation with Float32
// DO NOT EDIT - Changes will be overwritten

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Utilities.Structures.IndexSets;
using GeometricAlgebraFulcrumLib.Utilities.Structures.Dictionary;
using GeometricAlgebraFulcrumLib.Algebra.GeometricAlgebra.Basis;

namespace GeometricAlgebraFulcrumLib.Algebra.GeometricAlgebra.Float32;

public static class XGaFloat32Extensions
{
    /// <summary>
    /// Float32 wrapper for XGaParseTerms - converts double to float
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IEnumerable<(IndexSet, float)> XGaParseTermsFloat32(this string inputText)
    {
        foreach (var term in inputText.XGaParseTerms())
        {
            yield return (term.Item1, (float)term.Item2);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsValidVectorDictionary(this IReadOnlyDictionary<IndexSet, float> indexScalarDictionary)
    {
        return indexScalarDictionary.Count switch
        {
            0 => indexScalarDictionary is EmptyDictionary<IndexSet, float>,
            _ => indexScalarDictionary.All(p =>
                p.Key.Count == 1 &&
                float.IsFinite(p.Value) &&
                p.Value != 0f
            )
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsValidBivectorDictionary(this IReadOnlyDictionary<IndexSet, float> indexScalarDictionary)
    {
        return indexScalarDictionary.Count switch
        {
            0 => indexScalarDictionary is EmptyDictionary<IndexSet, float>,
            _ => indexScalarDictionary.All(p =>
                p.Key.Count == 2 &&
                float.IsFinite(p.Value) &&
                p.Value != 0f
            )
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsValidKVectorDictionary(this IReadOnlyDictionary<IndexSet, float> indexScalarDictionary, int grade)
    {
        return indexScalarDictionary.Count switch
        {
            0 => indexScalarDictionary is EmptyDictionary<IndexSet, float>,
            _ => indexScalarDictionary.All(p =>
                p.Key.Count == grade &&
                float.IsFinite(p.Value) &&
                p.Value != 0f
            )
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsValidMultivectorDictionary(this IReadOnlyDictionary<IndexSet, float> indexScalarDictionary)
    {
        return indexScalarDictionary.Count switch
        {
            0 => indexScalarDictionary is EmptyDictionary<IndexSet, float>,
            _ => indexScalarDictionary.All(p =>
                float.IsFinite(p.Value) &&
                p.Value != 0f
            )
        };
    }
}
";
    }

    private static string GenerateXGaVectorExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for XGa Vector/Multivector conversions

using System.Collections.Generic;
using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Algebra.GeometricAlgebra.Float32.Multivectors;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.SpaceND;

namespace GeometricAlgebraFulcrumLib.Algebra.GeometricAlgebra.Float32;

public static class XGaVectorFloat32Extensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector ToLinFloat32Vector(this XGaFloat32Vector vector)
    {
        var indexScalarDictionary = new Dictionary<int, float>();
        foreach (var (id, scalar) in vector.IdScalarPairs)
        {
            indexScalarDictionary[id.FirstIndex] = scalar;
        }
        return LinFloat32Vector.Create(indexScalarDictionary);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this Dictionary<int, float> indexScalarDictionary)
    {
        return LinFloat32Vector.Create(indexScalarDictionary);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this IReadOnlyDictionary<int, float> indexScalarDictionary)
    {
        return LinFloat32Vector.Create(indexScalarDictionary);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Vector CreateLinFloat32Vector(this int vSpaceDimensions)
    {
        return LinFloat32Vector.Create(vSpaceDimensions);
    }
}
";
    }

    private static string GenerateScalarExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Scalar utility extension methods for Float32
// DO NOT EDIT - Changes will be overwritten

using System;
using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Algebra.Scalars.Float32;

namespace GeometricAlgebraFulcrumLib.Algebra.Scalars.Float32;

public static class ScalarFloat32Extensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearZero(this double value, double epsilon = Float32Utils.ZeroEpsilon)
    {
        return Math.Abs(value) <= epsilon;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearZero(this float value, float epsilon = Float32Utils.ZeroEpsilon)
    {
        return Math.Abs(value) <= epsilon;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearEqual(this double value1, double value2, double epsilon = Float32Utils.ZeroEpsilon)
    {
        return Math.Abs(value1 - value2) <= epsilon;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearEqual(this float value1, float value2, float epsilon = Float32Utils.ZeroEpsilon)
    {
        return Math.Abs(value1 - value2) <= epsilon;
    }
}
";
    }

    private static string GenerateLinBasisVectorPair3DExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for LinBasisVectorPair3D to support Float32 Quaternion conversions
// DO NOT EDIT - Changes will be overwritten

using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Basis;
using GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32.Vectors.Space3D;
using GeometricAlgebraFulcrumLib.Algebra.Scalars.Float64;

namespace GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Basis;

public static class LinBasisVectorPair3DFloat32Extensions
{
    /// <summary>
    /// Float32 wrapper for VectorPairToVectorPairRotationQuaternion - converts double-based quaternion to float
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static LinFloat32Quaternion VectorPairToVectorPairRotationFloat32Quaternion(
        this LinBasisVectorPair3D srcVectorPair,
        LinBasisVectorPair3D dstVectorPair,
        double zeroEpsilon = Float64Utils.ZeroEpsilon)
    {
        // Call the Float64 version
        var float64Quaternion = srcVectorPair.VectorPairToVectorPairRotationQuaternion(dstVectorPair, zeroEpsilon);

        // Convert to Float32
        return LinFloat32Quaternion.Create(
            (float)float64Quaternion.Scalar,
            (float)float64Quaternion.ScalarI,
            (float)float64Quaternion.ScalarJ,
            (float)float64Quaternion.ScalarK
        );
    }
}
";
    }

    private static string GenerateRandomExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for Random Float32 utilities
// DO NOT EDIT - Changes will be overwritten

using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace GeometricAlgebraFulcrumLib.Utilities.Structures.Random;

public static class RandomFloat32Extensions
{
    /// <summary>
    /// Float32 wrapper for GetFloat64Numbers - generates float random numbers instead of double
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IEnumerable<float> GetFloat32Numbers(this System.Random randomGenerator, int count)
    {
        while (count > 0)
        {
            yield return (float)randomGenerator.GetFloat64();
            count--;
        }
    }

    /// <summary>
    /// Float32 wrapper for GetFloat64Numbers - generates float random numbers with min/max range
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IEnumerable<float> GetFloat32Numbers(this System.Random randomGenerator, int count, float minValue, float maxValue)
    {
        while (count > 0)
        {
            yield return (float)randomGenerator.GetFloat64(minValue, maxValue);
            count--;
        }
    }
}
";
    }

    private static string GenerateMathNetInteropExtensions()
    {
        return @"// <auto-generated />
// Generated by Float32Generator v1.0.0
// Extension Methods for MathNet.Numerics interop (double/Vector<double> types)
// DO NOT EDIT - Changes will be overwritten

using System.Runtime.CompilerServices;
using GeometricAlgebraFulcrumLib.Algebra.Scalars.Float32;
using MathNet.Numerics.LinearAlgebra;

namespace GeometricAlgebraFulcrumLib.Algebra.LinearAlgebra.Float32;

public static class MathNetInteropFloat32Extensions
{
    /// <summary>
    /// Check if a double value is near zero - for MathNet.Numerics interop
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearZero(this double value, float epsilon = Float32Utils.ZeroEpsilon)
    {
        return Math.Abs(value) < epsilon;
    }

    /// <summary>
    /// Check if a Vector double has near-zero L2 norm - for MathNet.Numerics interop
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearZero(this Vector<double> vector, float epsilon = Float32Utils.ZeroEpsilon)
    {
        return vector.L2Norm() < epsilon;
    }

    /// <summary>
    /// Check if a double value is near one - for MathNet.Numerics interop
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearOne(this double value, float epsilon = Float32Utils.ZeroEpsilon)
    {
        return Math.Abs(value - 1.0) < epsilon;
    }

    /// <summary>
    /// Check if two double values are nearly equal - for MathNet.Numerics interop
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNearEqual(this double value1, double value2, float epsilon = Float32Utils.ZeroEpsilon)
    {
        return Math.Abs(value1 - value2) < epsilon;
    }

    /// <summary>
    /// Convert Matrix float to Matrix Complex - for MathNet.Numerics interop
    /// MathNet.Numerics only has ToComplex() for Matrix double, not Matrix float
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Matrix<System.Numerics.Complex> ToComplex(this Matrix<float> matrix)
    {
        // Convert float matrix to double, then to complex
        return matrix.ToDouble().ToComplex();
    }

    /// <summary>
    /// Convert Vector float to Vector Complex - for MathNet.Numerics interop
    /// MathNet.Numerics only has ToComplex() for Vector double, not Vector float
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vector<System.Numerics.Complex> ToComplex(this Vector<float> vector)
    {
        // Convert float vector to double, then to complex
        return vector.ToDouble().ToComplex();
    }
}
";
    }
}
